### ISSUE TITLE
[documentation] Regarding python script

### ISSUE THREAD

**Issue by Angryl** [field69/Sample1#1]
Dear @field69 , 
I Just saw your ``` sample1``` repository, I really don't know that you really make a sample repository.
but i  found something in your ```python``` script
1. In _line number 10_  the browser **web driver** path the most important
2. and many more things how to setup a proper _readme file_ etc. etc.

**Comment by field69** [comment]
thank you for writing me up, 
do you want to collaborate with me and helping me in creating that?

**Comment by Angryl** [comment]
yeah sure it will be an honour.

**Comment by Angryl** [comment]
Dear @field69, 
now all the queries been resolved as we discussed. 
I generated the pull , that you merged successfully.
Thank You.
Happy Diwali.
@Angryl
